resolver: lts-11.9
packages:
  - mergeless
  - genvalidity-mergeless
extra-deps:
  - hlint-2.0.15
  - extra-1.6.5
  - git: https://github.com/NorfairKing/typed-uuid
    commit: 155c9ec880ca1c12f7dd8a8468b3626de8164823
    subdirs:
      - typed-uuid
      - genvalidity-typed-uuid
        
  - git: https://github.com/NorfairKing/validity
    commit: 226a0218502698447c191528826a2f54ba2ea20e
    subdirs:
      - validity
      - validity-containers
      - validity-path
      - validity-time
      - validity-uuid
      - genvalidity
      - genvalidity-containers
      - genvalidity-hspec
      - genvalidity-hspec-aeson
      - genvalidity-property
      - genvalidity-time
      - genvalidity-uuid

