resolver: lts-14.7
packages:
  - mergeless
  - genvalidity-mergeless
extra-deps:
  - github: NorfairKing/validity
    commit: a7be852cea9292ef2a618cb88ff823a53d926318
    subdirs:
      - validity
      - validity-containers
      - validity-path
      - validity-time
      - validity-uuid
      - genvalidity
      - genvalidity-containers
      - genvalidity-criterion
      - genvalidity-hspec
      - genvalidity-hspec-aeson
      - genvalidity-property
      - genvalidity-time
      - genvalidity-uuid

