resolver: lts-22.22
packages:
  - mergeless
  - genvalidity-mergeless
  - mergeless-persistent

extra-deps:
- github: NorfairKing/safe-coloured-text
  commit: 61f14d21b7399fe97da24e484c2f9fedaf532bb8
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-gen
- github: NorfairKing/autodocodec
  commit: b435803c3367b06c0d38acd90a54ba63e63fb6be
  subdirs:
    - autodocodec
    - autodocodec-nix
    - autodocodec-schema
    - autodocodec-yaml


system-ghc: true
nix:
  enable: false
with-hpack: hpack

