resolver: lts-19.6
packages:
  - mergeless
  - genvalidity-mergeless
  - mergeless-persistent
extra-deps:
  - github: NorfairKing/autodocodec
    commit: e337d681109cac273f5b9ea2b54b174bce79d312
    subdirs:
    - autodocodec
    - autodocodec-schema
    - autodocodec-yaml

  - github: NorfairKing/safe-coloured-text
    commit: 675cb01fce5f46718416d7746de5b856ed90a63f
    subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

  - github: NorfairKing/sydtest
    commit: ff224861ea409a9ee08576adb0438bbbb948917f
    subdirs:
    - sydtest
    - sydtest-discover

  - github: NorfairKing/validity
    commit: 2e9198bdaaa8c80a5dbe2b7b860b5c26558c6374
    subdirs:
    - validity
    - validity-aeson
    - validity-bytestring
    - validity-case-insensitive
    - validity-containers
    - validity-path
    - validity-persistent
    - validity-primitive
    - validity-scientific
    - validity-text
    - validity-time
    - validity-unordered-containers
    - validity-uuid
    - validity-vector
    - genvalidity
    - genvalidity-aeson
    - genvalidity-bytestring
    - genvalidity-case-insensitive
    - genvalidity-containers
    - genvalidity-criterion
    - genvalidity-path
    - genvalidity-persistent
    - genvalidity-property
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-sydtest-hashable
    - genvalidity-sydtest-lens
    - genvalidity-sydtest-persistent
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - genvalidity-uuid
    - genvalidity-vector

system-ghc: true
nix:
  enable: false
with-hpack: hpack

