resolver: lts-22.22
packages:
  - mergeless
  - genvalidity-mergeless
  - mergeless-persistent

extra-deps:
- github: NorfairKing/safe-coloured-text
  commit: 61f14d21b7399fe97da24e484c2f9fedaf532bb8
  subdirs:
  - safe-coloured-text
  - safe-coloured-text-layout
  - safe-coloured-text-gen
- github: NorfairKing/autodocodec
  commit: 36779707f38ec3aeb0a591ff8043a63717c96ea2
  subdirs:
    - autodocodec
    - autodocodec-yaml
    - autodocodec-schema

system-ghc: true
nix:
  enable: false
with-hpack: hpack

