resolver: lts-19.6
packages:
  - mergeless
  - genvalidity-mergeless
  - mergeless-persistent
extra-deps:
  - github: NorfairKing/autodocodec
    commit: 00649ce4174bc693de36077ffdfc3e0d7151ef08
    subdirs:
    - autodocodec
    - autodocodec-schema
    - autodocodec-yaml

  - github: NorfairKing/safe-coloured-text
    commit: 71c5940a3b84eeb498304d8e584e7638f875d51b
    subdirs:
    - safe-coloured-text
    - safe-coloured-text-terminfo

  - github: NorfairKing/sydtest
    commit: 263745786c277fab6d82ff6f48b6d745ade7a314
    subdirs:
    - sydtest
    - sydtest-discover

  - github: NorfairKing/validity
    commit: d88be911a7e2a84f6c089e9269aaed8d10a74acd
    subdirs:
    - validity
    - validity-aeson
    - validity-bytestring
    - validity-case-insensitive
    - validity-containers
    - validity-path
    - validity-persistent
    - validity-primitive
    - validity-scientific
    - validity-text
    - validity-time
    - validity-unordered-containers
    - validity-uuid
    - validity-vector
    - genvalidity
    - genvalidity-aeson
    - genvalidity-bytestring
    - genvalidity-case-insensitive
    - genvalidity-containers
    - genvalidity-criterion
    - genvalidity-path
    - genvalidity-persistent
    - genvalidity-property
    - genvalidity-scientific
    - genvalidity-sydtest
    - genvalidity-sydtest-aeson
    - genvalidity-sydtest-hashable
    - genvalidity-sydtest-lens
    - genvalidity-sydtest-persistent
    - genvalidity-text
    - genvalidity-time
    - genvalidity-unordered-containers
    - genvalidity-uuid
    - genvalidity-vector
nix:
  shell-file: shell.nix

