resolver: lts-13.19
packages:
  - mergeless
  - genvalidity-mergeless
extra-deps:
  - git: https://github.com/NorfairKing/validity
    commit: 8a13a23696115845133d87118b81c47fa1f9b04b
    subdirs:
      - validity
      - validity-containers
      - validity-path
      - validity-time
      - validity-uuid
      - genvalidity
      - genvalidity-containers
      - genvalidity-hspec
      - genvalidity-hspec-aeson
      - genvalidity-property
      - genvalidity-time
      - genvalidity-uuid

