name:                mergeless-persistent
version:             0.0.0.0
github:              "NorfairKing/mergeless"
license:             MIT
author:              "Tom Sydney Kerckhove"
maintainer:          "syd.kerckhove@gmail.com"
copyright:           "Copyright: (c) 2018-2020 Tom Sydney Kerckhove"
synopsis:            Support for using mergeless from persistent-based databases

dependencies:
  - base >= 4.11 && < 5

library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fwarn-redundant-constraints
  dependencies:
  - containers
  - mergeless
  - microlens
  - persistent

tests:
  mergeless-persistent-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - QuickCheck
      - containers
      - genvalidity >= 1.0
      - genvalidity-hspec
      - genvalidity-mergeless
      - genvalidity-persistent
      - hspec
      - mergeless
      - mergeless-persistent
      - monad-logger
      - mtl
      - path
      - path-io
      - persistent
      - persistent-sqlite
      - persistent-template
      - text
      - validity
