name: mergeless
version: 0.3.0.0
github: "NorfairKing/mergeless"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd.kerckhove@gmail.com"
copyright: "Copyright: (c) 2018-2022 Tom Sydney Kerckhove"

extra-source-files:
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/NorfairKing/mergeless#readme>


library:
  source-dirs: src
  ghc-options:
  - -Wall
  - -fwarn-redundant-constraints
  dependencies:
  - aeson
  - autodocodec
  - base >= 4.11 && < 5
  - containers
  - deepseq
  - mtl
  - text
  - validity
  - validity-containers
