name: genvalidity-mergeless
version: 0.4.0.0
github: "NorfairKing/mergeless"
license: MIT
author: "Tom Sydney Kerckhove"
maintainer: "syd.kerckhove@gmail.com"
copyright: "Copyright: (c) 2018-2022 Tom Sydney Kerckhove"

extra-source-files:
- ChangeLog.md
- test_resources/**/*

description:         Please see the README on GitHub at <https://github.com/NorfairKing/mergeless#readme>


library:
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
    - QuickCheck
    - containers
    - genvalidity >=1.0
    - genvalidity-containers
    - genvalidity-time
    - mergeless >=0.2.0.0

tests:
  mergeless-test:
    main: Spec.hs
    source-dirs: test
    build-tools: sydtest-discover
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - QuickCheck
      - autodocodec
      - autodocodec-yaml
      - base >= 4.7 && < 5
      - containers
      - genvalidity-mergeless
      - genvalidity-sydtest
      - genvalidity-sydtest-aeson
      - genvalidity-uuid
      - mergeless
      - mtl
      - safe-coloured-text
      - sydtest
      - pretty-show
      - random
      - time
      - uuid

benchmarks:
  genvalidity-mergeless-bench:
    main:                Bench.hs
    source-dirs:         bench
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - criterion
      - genvalidity-criterion
      - genvalidity-mergeless
      - mergeless
