name:                genvalidity-mergeless
version:             0.0.0.0
github:              "NorfairKing/mergeless"
license:             MIT
author:              "Tom Sydney Kerckhove"
maintainer:          "syd.kerckhove@gmail.com"
copyright:           "Copyright: (c) 2018 Tom Sydney Kerckhove"

extra-source-files:
- README.md
- ChangeLog.md

description:         Please see the README on GitHub at <https://github.com/NorfairKing/mergeless#readme>


library:
  source-dirs: src
  dependencies:
    - base >= 4.7 && < 5
    - QuickCheck
    - genvalidity
    - genvalidity-containers
    - genvalidity-time
    - genvalidity-typed-uuid
    - mergeless

tests:
  genvalidity-mergeless-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
      - base >= 4.7 && < 5
      - genvalidity-hspec
      - genvalidity-hspec-aeson
      - genvalidity-mergeless
      - hspec
      - mergeless
